#!/usr/bin/env ruby

require 'gosu'
require_relative 'levels'
require_relative 'playerShip'
require_relative 'enemyShip'


class GameWindow < Gosu::Window
  def initialize
    super 640, 480
    self.caption = "RAPTOR v0.0.1"

	#@levels = Levels.new(self)
	#@current_level = @levels.get_level(0)	
  	@playerShip = PlayerShip.new(self)
	@enemyShip = EnemyShip.new(self)
  end

  def update
	#@current_level.update
  	@playerShip.update
	@enemyShip.update
	@playerShip.balls.each do |ball|
		ball.hit = @enemyShip.hit(ball.x,ball.y) if !ball.hit
	end
  end

  def draw
  	#@current_level.draw
	@playerShip.draw
	@enemyShip.draw
  end
  
  def needs_cursor?
    false
  end

  def button_down(id)
	@playerShip.button_down(id)
  end

  def button_up(id)
	@playerShip.button_up(id)
  end
end







window = GameWindow.new
window.show

###


